version: '3.8'

services:
  nest-api-prod:
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    container_name: nest-api-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
        /home/node/app/dist
        /home/node/app/node_modules

    depends_on:
      - postgres
    env_file:
      - .env
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
