version: '3.8'

services:
  nest-api-prod:
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"
    container_name: nest-api-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules

    depends_on:
      - postgres
    env_file:
      - .env
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - DATABASE_URL=postgresql://postgres:b*25Bddc-fdcE6CAAFcbB5A61C4D1Bd5@monorail.proxy.rlwy.net:43307/railway
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGDATABASE=railway
      - PGHOST=monorail.proxy.rlwy.net
      - PGPASSWORD=b*25Bddc-fdcE6CAAFcbB5A61C4D1Bd5
      - POSTGRES_DB=railway
      - POSTGRES_PASSWORD=postgres
      - PGPORT=43307
      - POSTGRES_PASSWORD
      - SSL_CERT_DAYS=820
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
